# Generated by Django 5.0 on 2024-02-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
