# Generated by Django 5.0 on 2024-02-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_portfoliofinancialinstrument_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
