# Generated by Django 5.0 on 2024-02-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_portfoliofinancialinstrument_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstrument',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Close'), (2, 'Ready'), (3, 'Pending'), (4, 'Delete')], default=0),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Close'), (2, 'Ready'), (3, 'Pending'), (4, 'Delete')], default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Close'), (2, 'Ready'), (3, 'Pending'), (4, 'Delete')], default=0),
        ),
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Close'), (2, 'Ready'), (3, 'Pending'), (4, 'Delete')], default=0),
        ),
    ]
