# Generated by Django 5.0 on 2024-02-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_financialinstrument_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliofinancialinstrument',
            name='sell_date',
        ),
        migrations.RemoveField(
            model_name='portfoliofinancialinstrument',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='portfoliofinancialinstrument',
            name='sell_quantity',
        ),
        migrations.AddField(
            model_name='portfoliofinancialinstrument',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PortfolioFinancialInstrumentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('sell_quantity', models.IntegerField(blank=True, default=0)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('portofolio_financial_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.portfoliofinancialinstrument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
