# Generated by Django 5.0 on 2023-12-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='sell_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
