# Generated by Django 5.0 on 2023-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_portfoliofinancialinstrument_sell_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='buy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='sell_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
