# Generated by Django 5.0 on 2023-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_portfoliofinancialinstrument_buy_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='buy_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
