# Generated by Django 5.0 on 2023-12-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_portfoliofinancialinstrument_buy_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangefees',
            name='instrument',
            field=models.IntegerField(choices=[(0, 'Cripto'), (1, 'Cedear'), (2, 'Stock'), (3, 'Bono'), (4, 'Caucion'), (5, 'Fondo comun de inversion')], default=0),
        ),
    ]
