# Generated by Django 5.0 on 2023-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_exchangefees_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangefees',
            name='fees',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
