# Generated by Django 5.0 on 2023-12-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_exchangefees_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstrumentapidata',
            name='variation',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
