# Generated by Django 5.0 on 2023-12-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_financialinstrumentapidata_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinstrument',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Close'), (2, 'Ready'), (3, 'Pending')], default=0),
        ),
    ]
