# Generated by Django 5.0 on 2023-12-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_financialinstrument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstrumentapidata',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialinstrumentapidata',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
