# Generated by Django 5.0 on 2023-12-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_financialinstrumentapidata_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofinancialinstrument',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
