# Generated by Django 5.0 on 2023-12-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_financialinstrumentapidata_actual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliofinancialinstrument',
            name='fees',
        ),
    ]
