FINANCIAL_INSTRUMENTS = [
    {"type":1, "symbol": "ADBE", "name": "ADOBE SYSTEMS INCORPORATED"},
    {"type":1, "symbol": "TSLA", "name": "TESLA, INC"},
    {"type":1, "symbol": "AMZN", "name": "AMAZON.COM, INC"},
    {"type":1, "symbol": "CRM", "name": "SALESFORCE.COM, INC"},
    {"type":1, "symbol": "NKE", "name": "NIKE INC"},
    {"type":1, "symbol": "RBLX", "name": "ROBLOX CORP"},
    {"type":1, "symbol": "NVDA", "name": "NVIDIA CORPORATION"},
    {"type":1, "symbol": "ERJ", "name": "EMBRAER"},
    {"type":1, "symbol": "MELI", "name": "MERCADOLIBRE"},
    {"type":1, "symbol": "VIST", "name": "VISTA OIL & GAS"},
    {"type":1, "symbol": "BIIB", "name": "BIOGEN INC"},
    {"type":1, "symbol": "META", "name": "META PLATFORMS INC"},
    {"type":1, "symbol": "GOGLC", "name": "GOOGLE INC"},
    {"type":1, "symbol": "VALE", "name": "COMPANHIA VALE DO RIO DOCE"},
    {"type":1, "symbol": "EA", "name": "ELECTRONIC ARTS INC"},
    {"type":2, "symbol": "YPFD", "name": "YPF S.A. ESCRIT. 'D' 1 VOTO"},
    {"type":2, "symbol": "PAMP", "name": "PAMPA ENERGIA"},
    {"type":2, "symbol": "TGSU2", "name": "T. DE GAS DEL SUR ESC. 'B' 1 V."},
    {"type":2, "symbol": "CRES", "name": "CRESUD S.A. ORDS. 1 VOTO ESCRITURALES"},
    {"type":2, "symbol": "LOMA", "name": "ACC.ORD. LOMA NEGRA S.A. 1 VOTO $ ESC."},
    {"type":0, "symbol": "INJ", "name": "INJECTIVE"},
    {"type":0, "symbol": "MATIC", "name": "MATIC"},
    {"type":0, "symbol": "BTC", "name": "BITCOIN"},
    {"type":0, "symbol": "NAKA", "name": "NAKAMOTO GAMES"},
    {"type":0, "symbol": "XCAD", "name": "XCAD NETWORK"},
    {"type":0, "symbol": "ZIL", "name": "ZILLIQA"},
    {"type":0, "symbol": "ETH", "name": "ETHEREUM"},
    {"type":0, "symbol": "CRV", "name": "CURVE DAO TOKEN"},
    {"type":0, "symbol": "AAVE", "name": "AAVE TOKEN"},
    {"type":0, "symbol": "BNB", "name": "BINANCE TOKEN"},
    {"type":0, "symbol": "KSM", "name": "KUSAMA TOKEN"},
    {"type":0, "symbol": "FLOW", "name": "FLOW TOKEN"},
    {"type":0, "symbol": "NEAR", "name": "NEAR PROTOCOL"},
    {"type":0, "symbol": "SOL", "name": "SOLANA TOKEN"},
    {"type":0, "symbol": "LUNA", "name": "LUNA TOKEN"},
    {"type":0, "symbol": "LUNAC", "name": "LUNA CLASSIC TOKEN"},
    {"type":0, "symbol": "OCEAN", "name": "OCEAN PROTOCOL"},
]

EXCHANGES_FEES = {
    "binance":"0.1",
    "balanz":"0.0082"
}